name: CMake Build and Test

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "include/**"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "include/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libgmp-dev libssl-dev libboost-all-dev
          sudo apt-get install -y nlohmann-json3-dev

      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: |
          cmake --build build -- -j$(nproc)

      - name: Run tests
        run: |
          ctest --test-dir build --output-on-failure
